#开启debug模式，可以打印出自动配置启用情况
#debug: true
spring:
  profiles:
    active: test
---
server:
  port: 8888
  tomcat: 
     uri-encoding: UTF-8
#  ssl:
#    key-store: classpath:1956183_www.wangmx.cn.pfx
#    key-store-password: iKJi69pJ
#    key-store-type: PKCS12
#condition:
#  http2https: true
bloger:
    boy: 21
    gril: 20
file:
    staticAccessPath: /upload/**
    uploadFolder: /image/upload
 
spring:
    profiles: test
    thymeleaf:
      cache: false
      mode: LEGACYHTML5
    datasource:
        username: root
        password: admin
        url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2B8&useSSL=true
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
      
    http:
        encoding: 
            charset: UTF-8 
            enabled: true
            force: true
   
    servlet: 
      multipart:
        max-file-size: 5MB
        max-request-size: 5MB

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.xiao.blog.model  # 注意：对应实体类的路径

logging:
  path: logger
  level: 
     com.blog.mapper: debug
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    currentPage: 0
    pageSize: 6

   

###生产环境配置   
---
server:
  port: 8080
  tomcat: 
     uri-encoding: UTF-8
condition: 
  http2https: true 

http: 
  port: 80
file:
    staticAccessPath: /upload/**
    uploadFolder: /image/upload
 
spring:
    profiles: prod
    datasource:
        username: root
        password: admin
        url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2B8
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
      
    http:
        encoding: 
            charset: UTF-8 
            enabled: true
            force: true
   
    servlet: 
      multipart:
        max-file-size: 5MB
        max-request-size: 5MB
    thymeleaf:
       cache: false
       mode: LEGACYHTML5
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.blog.model  # 注意：对应实体类的路径

logging:
  path: logger
  level: 
     com.blog.mapper: debug
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    currentPage: 0
    pageSize: 5

    